osdj/osb/urls.py
from django.conf.urls import patterns, url

from osb import views

urlpatterns = patterns('',
	
	url(r'^$', views.index, name="index"),
	url(r'^chat/$', views.chat, name="chat"),

	#user registry 
	url(r'^registration/$', views.registration, name="registration"),
	url(r'^registry/$', views.registry, name="registry"),
	url(r'^profile/$', views.profile, name="profile"),
	url(r'^home/(?P<username>\w+)/$', views.home, name="home"),
	url(r'^checkUsername/(?P<username>\w+)/$', views.checkUsername, name="checkUsername"),
	
	#chat ajax method
	url(r'^getFromuser/$', views.getFromuser, name="getFromuser"),
	url(r'^checkMessageNumber/$', views.checkMessageNumber, name="checkMessageNumber"),
	url(r'^sendMessage/(?P<userid>\d+)/$', views.sendMessage, name="sendMessage"),
	url(r'^getMessage/(?P<fuserid>\d+)/$', views.getMessage, name="getMessage"),
	url(r'^setMessageReaded/(?P<messageid>\d+)/$', views.setMessageReaded, name="setMessageReaded"),
)

osdj/osdj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
urlpatterns = patterns('',
    # Examples:
    url(r'^admin/', include(admin.site.urls)),
	url(r'accounts/login/$', auth_views.login, {'template_name': 'osb/login.html'}),
	url(r'accounts/logout/$', auth_views.logout, {'template_name': 'osb/logout.html'}),
    url(r'^osb/', include('osb.urls')),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
				{'document_root': settings.MEDIA_ROOT,}),
)

osdj/osb/models.py
# -*- coding:utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
###############################
#FileName	: models.py
#Location	: app_olb(应用——olb)
#CreateDate	: 2014-10-28
#Author		: AmzingPoint
###############################

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import (
	BaseUserManager, AbstractBaseUser
)

class OsbUserManager(BaseUserManager):
	#override the create_user
	def create_user(self, username, password=None):
		user = self.model(				           
			username=username,
		)
		user.set_password(password)
		user.save(using=self._db)
		return user
	#override the create_superuser
	def create_superuser(self, username, password=None):
		user = self.create_user(username, password)
		user.is_admin = True
		user.save(using=self._db)
		return user

class User(AbstractBaseUser):
	'''The information for user, 用户基本信息'''
	username = models.CharField('用户名', max_length=48, unique=True)
	truename = models.CharField('真名', max_length=32, null=True, blank=True)
	nowcity = models.CharField('现居城市', max_length=42, null=True, blank=True)
	soldiercity = models.CharField('服役地点', max_length=42, null=True, blank=True)
	joindate = models.DateField('入伍年份', null=True, blank=True)
	email = models.EmailField('邮箱', max_length=128, null=True, blank=True)
	sex = models.CharField('性别', max_length=4, null=True, blank=True)
	birthday = models.DateField('生日', null=True, blank=True)
	telphone = models.CharField('电话', max_length=14, null=True, blank=True)
	picture = models.ImageField('头像', upload_to='userImages', default="default.jpg")
	is_active = models.BooleanField(default=True)
	is_admin = models.BooleanField(default=False)
	following = models.ManyToManyField('self','关注的人')
		
	objects = OsbUserManager()

	USERNAME_FIELD = 'username'

	def get_full_name(self):
		return self.username
	
	def get_short_name(self):
		return self.username

	def __unicode__(self):
		return self.username
	
	def has_perm(self, perm, obj=None):
		'检查用户是否具有权限'
		return True
	
	def has_module_perms(self, app_label):
		'检查用户是否具有某个app的权限'
		return True
	
	@property
	def is_staff(self):
		return self.is_admin

	class Meta:
		verbose_name_plural = '用户'


class Group(models.Model):
	'''The grop table one group have one leader who comes 
	from user, A group and be join with users
	小组表，一个小组只能有一个组长，小组与组长为一对多关系
	小组同时可以被多个用户加入, 小组与用户为多对多关系'''
	name = models.CharField('小组名称', max_length=32)
	leader = models.ForeignKey(User, verbose_name='组长')
	member = models.ManyToManyField(User, related_name='groupmemberuser', null=True, blank=True)
	createdate = models.DateTimeField('创建时间', null=True, blank=True)
	description = models.CharField('描述', max_length=360)
	image = models.ImageField('展示图片', upload_to='groupImages', null=True, blank=True)
	def __unicode__(self):
		return self.name
	class Meta:
		verbose_name_plural = '小组'

class Topics(models.Model):
	'''The topics must pub in a group and users can give 
	a heart, the realation-ship from topics to group is 
	many2One and with users who like it is one2many
	一个话题必须发布在一个小组里，用户可以给话题点赞，话题和
	小组之间是多对一关系，和点赞的用户之间时多对多关系'''
	headline = models.CharField('话题标题', max_length=128)
	description = models.CharField('话题描述', max_length=512)
	group = models.ForeignKey(Group, verbose_name='所属小组' )
	creator = models.ForeignKey(User, verbose_name='创建者')
	likeduser = models.ManyToManyField(User, verbose_name='喜欢的人',  related_name='likegroupuser', null=True, blank=True)
	createdate = models.DateTimeField('创建时间', default=timezone.now())
	def __unicode__(self):
		return self.headline
	class Meta:
		verbose_name_plural = '话题'

class  Comment(models.Model):
	'''Comments have a id that which topics be commented
	a pice of comment can also be liked by other user
	评论表，一条评论对应一个话题，和话题为多对一关系
	一个用户可以多次评论，评论与用户为多对多关系
	评论还可以被用户点赞，此时评论与点赞用户为一对多关系'''
	content = models.CharField('评论内容', max_length=1024)
	topics = models.ForeignKey(Topics)
	commenter = models.ForeignKey(User, verbose_name='评论者', related_name='commentcommentuser')
	likeduser = models.ManyToManyField(User, verbose_name='喜欢的用户', related_name='likecommentsuser')
	createdate = models.DateTimeField('评论时间')
	father = models.ForeignKey('self', null=True, blank=True,verbose_name='回复评论')
	def __unicode__(self):
		return self.content[0:10]
	class Meta:
		verbose_name_plural = '评论'


class ChatMessage(models.Model):
	'''Chat Message is a user and another chat
	聊天信息是一个用户和另一个用户之间聊天的内容'''
	message = models.CharField('聊天内容', max_length=128)
	fromuser = models.ForeignKey(User, verbose_name='发送方', related_name='sender')
	touser = models.ForeignKey(User, verbose_name='接收方', related_name='receiver')
	createtime = models.DateTimeField('发送时间', default=timezone.now())
	is_read = models.BooleanField(default=False)
	def __unicode__(self):
		return self.message
	class Meta:
		verbose_name_plural = '站内私信'

osdj/osb/views.py
# -*- coding:utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
###############################
#FileName	: models.py
#Location	: app_olb(应用——olb)
#CreateDate	: 2014-10-29
#Author		: AmzingPoint
###############################

from django.shortcuts import render, render_to_response
from osb.models import *
from django.contrib.auth import authenticate,login,hashers 
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.template.loader import get_template
from django.template import Context



def index(request):
	user = request.user
	if user.is_authenticated():
		return HttpResponseRedirect('/osb/home/'+user.username)
	'''获取用户最喜欢的8个话题
	get 7 top topics'''
	top_topics_list = Topics.objects.\
			annotate(num_likeduser=Count('likeduser')).\
			order_by('-num_likeduser')[0:8]
	'''获取最新加入的7个用户
	get 7 new user'''
	recent_user_list = User.objects.order_by('-id')[0:7]
	'''获取成员最多的7个小组
	get 7 group which have more member'''
	top_group_list = Group.objects.\
			annotate(num_member=Count('member')).\
			order_by('-num_member')[0:7]
	return render(request, 'osb/index.html', locals())

def home(request, username):
	'''用户主页
	user's own page'''
	user = request.user
	if(user.username == username):
		user_following_topics_list = Topics.objects.filter(creator = user.following.all())[0:30]
		user_group_list = Group.objects.filter(leader = user)
		user_added_group_list = Group.objects.filter(member = user)
		user_topics_list = Topics.objects.filter(creator=user)[0:30]
		return render(request, 'osb/home.html', locals())
	else:
		show_user = User.objects.get(username=username)
		user_group_list = Group.objects.filter(leader=show_user)
		user_topics_list = Topics.objects.filter(creator=show_user)[0:30]
		return render(request, 'osb/customer_home.html', locals())


#registry
def registration(request):
	'''用户注册
	user registration'''
	username = request.POST['username']
	password_unmake = request.POST['password1']
	password = hashers.make_password(password_unmake)
	new_user = User(username=username, password=password)
	new_user.save()
	user = authenticate(username=username, password=password_unmake)
	if user is not None:
		login(request,user)
		print(user)
		return HttpResponseRedirect('/osb/index')
	else:
		return HttpResponseRedirect('/osb/registry')

def registry(request):
	return render(request, 'osb/registry.html')

def profile(request):
	return render(request, 'osb/index.html')

def checkUsername(request, username):
	count = User.objects.filter(username=username).count()
	print("################################# %d",count)
	return HttpResponse(count)

#IM
def chat(request):
	'''获取朋友列表
	get friendlist'''
	user = request.user
	friend_list = user.following.filter(following=user)
	return render(request, 'osb/chat.html', locals())

def getFromuser(request):
	'''获取发送消息且消息没被读取的用户
	get the friend who sent message to you'''
	user = request.user
	messages = ChatMessage.objects.filter(touser=user).filter(is_read=False)
	message_list = list(messages)
	friend_list = []
	for message in message_list:
		if(message.fromuser not in friend_list):
			friend_list.append(message.fromuser)
	t = get_template('osb/chat_friend.html')
	html = t.render(Context({'unread_friend_list': friend_list }))
	return HttpResponse(html)

def sendMessage(request, userid):
	'''发送信息到服务器
	send message to server'''
	fu = request.user
	tu = User.objects.get(pk=userid)
	msg = request.GET['message']
	cm = ChatMessage(fromuser=fu, touser=tu, message=msg)
	cm.save()
	return HttpResponse("success")

def getMessage(request, fuserid):
	'''从服务器获取最新的未读消息
	get new unread  message '''
	touser = request.user
	fuser = User.objects.get(pk=fuserid)
	message = ChatMessage.objects.filter(touser=touser).filter(fromuser=fuser).filter(is_read=False).order_by('id')
	data = serializers.serialize("json", message)
	return HttpResponse(data, content_type='application/json')

def setMessageReaded(request, messageid):
	'''设置消息状态为已读
	set the message is readed'''
	message = ChatMessage.objects.get(pk=messageid)
	message.is_read = True
	message.save()
	return True

def checkMessageNumber(request):
	'''从服务器获取未读消息的数量
	get the message number which not be readed'''
	user = request.user
	number = ChatMessage.objects.filter(touser=user).filter(is_read=False).count()
	print(number)
	return HttpResponse(number)

osdj/osb/templates/osb/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="UTF-8">
	<!-- bootstrap -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
	<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
	<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="{% static "js/osb_base.js" %}"></script>
	<link rel="stylesheet" href='{% static 'css/style.css' %}'>
	<!-- endbootsrap -->
	<title>OLD SOLDIER</title>
</head>
<body>
<!-- nav bar -->
<nav class="navbar navbar-custom navbar-static-top" role="navigation">
<div class="container">
<!--mobile-->
<div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="/osb">LAOBING</a>
</div>
<!--/header-->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<ul class="nav navbar-nav">
		<li><a href="#">寻找老伙伴</a></li>
		<li><a href="#">发现小组</a></li>
		<li><a href="#">老兵圈</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
		{% if user.is_authenticated %}
		<li><a href="/osb/chat">私信<span id="messageCount" class='badge badge-orange'></span></a>
		</li>
		<li><a href="/osb/home/{{user.username}}">{{ user.username }}</a></li>
		<li><a href="accounts/logout">注销</a></li>
		{% else %}
		<li><a href="accounts/login">登录</a></li>
		<li><a href="/osb/registry">注册</a></li>
		{% endif %}
	</ul>
</div><!--/collapse-->
</div><!--/container-->
</nav><!--/nav-->

<div class="container" style="margin-top:40px;">
	
	<div class="row">
		{% block content %}
		{% endblock %}

		{% block right %}
		{% endblock %}
	</div>
</div>

</body>
</html>

osdj/osb/templates/osb/chat_friend.html
<script>
	//更改接收方（touser）
	$(".unread-list-friend").click(function(){
		friendid = $(this).attr("data-friendid");
		friend = $(this).attr("data-friend");
		friendpicture = $(this).attr("data-friendpicture");
		$(".panel-title").text(friend);	
		$(".chat-body").html(null)
		$(this).css("background-color", "#339966").siblings().css("background-color", "#eee");
		$(this).fadeOut()
		//每三秒pull
		setInterval("getMessage()",3000)
	});
</script>

{% for friend in unread_friend_list %}
<div class="list-friend unread-list-friend" data-friendid="{{ friend.id}}" data-friend="{{ friend }}" data-friendpicture="{{ friend.picture }}">
<img class="img-circle" src="{{ friend.picture.url }}">
<p> {{ friend.username }}</p>
<span class="badge" style="background:#cc0000;">新消息</span>
</div>
{% endfor %}

osdj/osb/templates/osb/customer_home.html
{% extends "osb/base.html"%}
{% load static from staticfiles %}
{% block content %}
<div class="col-md-9" style="margin-top:-20px;">
	<div class="col-md-4 visible-md-block visible-lg-block">
		<img src="{{ show_user.picture.url }}" class="user-picture img-rounded"/>
		<h4><b>{{ show_user.username }}</b></h4>
    <hr>
    
    {% if show_user.email %}
    <p><span class="glyphicon glyphicon-envelope"></span><a href="#">{{ show_user.email }}</a></p>
    {% endif %}
    {% if show_user.nowcity %}
    <p><span class="glyphicon glyphicon-home"></span><a href="#">{{ show_user.nowcity }}</a></p>
    {% endif %}
    {% if show_user.joindate %}
    <p><span class="glyphicon glyphicon-time"></span><a href="#">{{ show_user.joindate }}</a></p>
    {% endif %}
    <hr>
    <div class="user-info"><a>{{ show_user.group_set.count }}</a> <p>小组</p></div>
    <div class="user-info"><a>{{ show_user.topics_set.count }}</a> <p>话题</p></div>
    <div class="user-info"><a>{{ show_user.following.count }}</a> <p>关注</p></div>
	</div>

	<div class="col-md-8">
         <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-tabs-green " role="tablist">
      <li role="presentation" class="active"><a href="#group" role="tab" data-toggle="tab">他的小组</a></li>
      <li role="presentation"><a href="#topics" role="tab" data-toggle="tab">他的话题</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">

      <div role="tabpanel" class="tab-pane fade in active" id="group">
		<h4>{{ show_user.username }}的小组</h4>
          {% for group in user_group_list %}
          <div class="panel panel-following-group-normal  ">
            <div class="panel-body">
              <a href="#">{{ group.name }}</a> &nbsp;&nbsp;
              {{ group.member.count }}成员 &nbsp;&nbsp;   
              {{ group.topics_set.count }}话题&nbsp;&nbsp;   
			  <a href="#">加入小组</a>
            </div>
          </div>  
          {% endfor %}

        <div class="panel panel-following-group-normal  ">
           <div class="panel-body">
             <a href="#">发现其他小组</a>    
           </div>
        </div>  
      </div>
      

      <div role="tabpanel" class="tab-pane fade " id="topics">
		    {% for topics in user_topics_list %}
          <div class="panel panel-following-topic-normal  ">
            <div class="panel-body">
                <div class="user-custom-left">
                  <img src="{{ topics.creator.picture.url }}" class="user-custom-picture img-rounded" />
                  <a>{{ topics.creator.username }}</a>
                </div>
                <div class="user-custom-right">
                  发布于<a>{{topics.group}}</a> 
                  <p>{{ topics.description }}</p>
                <a><span class="glyphicon glyphicon-edit"></span></a>
                <a><span class="glyphicon glyphicon-star-empty"></span>{{ topics.likeduser.count }}</a>
                 <em>{{ topics.createdate }}</em>
                </div>
            </div>
          </div>  
        {% endfor %}
      </div>

    </div>
	</div>		
</div>
{% endblock %}

<!--right on desktop-->
{% block right%}
<div class="col-md-3" style="margin-top:-20px;">
  <div class="panel panel-default">
    <div class="panel-heading">
        创建一个话题...
    </div>
    <div class="panel-body">
        <textarea class="field span12" id="textarea" rows="5" placeholder="三句话  能搞定否"></textarea>
        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
          在小组中发布<span class="caret"></span>
        </button>
        <a href="#" class="btn btn-success" style="float:right;" role="button">发布</a>
    </div>
  </div>

  <div class="panel panel-primary">
    <div class="panel-heading">
        加入一个小组...
    </div>
    <div class="panel-body" style="padding:5px;">
      <a href="#" class="btn btn-primary " role="button">地球人联盟</a>
      <a href="#" class="btn btn-primary " role="button">我们在北京</a>
      <a href="#" class="btn btn-primary " role="button">同志热恋</a>
      <a href="#" class="btn btn-primary " role="button">好好学习 天天向上</a>
      <a href="#" class="btn btn-primary " role="button">大学党 伤不起</a>
      <a href="#" class="btn btn-primary " role="button">官方小组</a>
      <a href="#" class="btn btn-primary " role="button">好好学习 天天向上</a>
      <a href="#" class="btn btn-primary " role="button">大学党 伤不起</a>
      <a href="#" class="btn btn-primary " role="button">官方小组</a>
      <a href="#" class="btn btn-primary " role="button">好好学习 天天向上</a>
    </div>
  </div>

</div>
{% endblock %}

osdj/osb/templates/osb/home.html
{% extends "osb/base.html"%}
{% load static from staticfiles %}
{% block content %}
<div class="col-md-9" style="margin-top:-20px;">
	<div class="col-md-4 visible-md-block visible-lg-block">
		<img src="{{ user.picture.url }}" class="user-picture img-rounded"/>
		<h4><b>{{ user.username }}</b></h4>
    <hr>
    {% if user.email %}
    <p><span class="glyphicon glyphicon-envelope"></span><a href="#">{{ user.email }}</a></p>
    {% endif %}
    {% if user.nowcity %}
    <p><span class="glyphicon glyphicon-home"></span><a href="#">{{ user.nowcity }}</a></p>
    {% endif %}
    {% if user.joindate %}
    <p><span class="glyphicon glyphicon-time"></span><a href="#">{{ user.joindate }}</a></p>
    {% endif %}
    <hr>
    <div class="user-info"><a>{{ user.group_set.count }}</a> <p>小组</p></div>
    <div class="user-info"><a>{{ user.topics_set.count }}</a> <p>话题</p></div>
    <div class="user-info"><a>{{ user.following.count }}</a> <p>关注</p></div>
	</div>

	<div class="col-md-8">
         <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-tabs-green " role="tablist">
      <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">我关注的人</a></li>
      <li role="presentation"><a href="#group" role="tab" data-toggle="tab">我的小组</a></li>
      <li role="presentation"><a href="#topics" role="tab" data-toggle="tab">我的话题</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="home">
        {% for topics in user_following_topics_list %}
          <div class="panel panel-following-topic-normal  ">
            <div class="panel-body">
                <div class="user-custom-left">
                  <img src="{{ topics.creator.picture.url }}" class="user-custom-picture img-rounded" />
				  <a href="/osb/home/{{topics.creator.username}}">{{ topics.creator.username }}</a>
                </div>
                <div class="user-custom-right">
                  发布于<a>{{topics.group}}</a> 
                  <p>{{ topics.description }}</p>
                <a><span class="glyphicon glyphicon-edit"></span></a>
                <a><span class="glyphicon glyphicon-star-empty"></span>{{ topics.likeduser.count }}</a>
                 <em>{{ topics.createdate }}</em>
                </div>
            </div>
          </div>  
        {% endfor %}
      </div>
     

      <div role="tabpanel" class="tab-pane fade" id="group">
        
        <div class="col-md-6" style="margin-top:20px;">
          <h4>我创建的小组</h4>
          {% for group in user_group_list %}
          <div class="panel panel-following-group-normal  ">
            <div class="panel-body">
              <a href="#">{{ group.name }}</a> &nbsp;&nbsp;
              {{ group.member.count }}成员 &nbsp;&nbsp;   
              {{ group.topics_set.count }}话题   
            </div>
          </div>  
          {% endfor %}
          <div class="panel panel-following-group-normal  ">
            <div class="panel-body">
              <a href="#">创建新的小组</a>         
            </div>
          </div>  
        </div>

        <div class="col-md-6" style="margin-top:20px;">
          <h4>我加入的小组</h4>
          {% for group in user_added_group_list%}
          <div class="panel panel-following-group-normal  ">
            <div class="panel-body">
              <a href="#">{{ group.name }} </a> &nbsp; &nbsp;
              小组长<a href="#">{{ group.leader }}</a>               
            </div>
          </div>  
          {% endfor %}
          <div class="panel panel-following-group-normal  ">
            <div class="panel-body">
              <a href="#">发现其他小组</a>    
            </div>
          </div>  
        </div>
      </div>
      

      <div role="tabpanel" class="tab-pane fade" id="topics">
		    {% for topics in user_topics_list %}
          <div class="panel panel-following-topic-normal  ">
            <div class="panel-body">
                <div class="user-custom-left">
                  <img src="{{ user.picture.url }}" class="user-custom-picture img-rounded" />
                  <a>{{ topics.creator.username }}</a>
                </div>
                <div class="user-custom-right">
                  发布于<a>{{topics.group}}</a> 
                  <p>{{ topics.description }}</p>
                <a><span class="glyphicon glyphicon-edit"></span></a>
                <a><span class="glyphicon glyphicon-star-empty"></span>{{ topics.likeduser.count }}</a>
                 <em>{{ topics.createdate }}</em>
                </div>
            </div>
          </div>  
        {% endfor %}
      </div>

    </div>
	</div>		
</div>
{% endblock %}

<!--right on desktop-->
{% block right%}
<div class="col-md-3" style="margin-top:-20px;">
  <div class="panel panel-default">
    <div class="panel-heading">
        创建一个话题...
    </div>
    <div class="panel-body">
        <textarea class="field span12" id="textarea" rows="5" placeholder="三句话  能搞定否"></textarea>
        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
          在小组中发布<span class="caret"></span>
        </button>
        <a href="#" class="btn btn-success" style="float:right;" role="button">发布</a>
    </div>
  </div>

  <div class="panel panel-primary">
    <div class="panel-heading">
        加入一个小组...
    </div>
    <div class="panel-body" style="padding:5px;">
      <a href="#" class="btn btn-primary " role="button">地球人联盟</a>
      <a href="#" class="btn btn-primary " role="button">我们在北京</a>
      <a href="#" class="btn btn-primary " role="button">同志热恋</a>
      <a href="#" class="btn btn-primary " role="button">好好学习 天天向上</a>
      <a href="#" class="btn btn-primary " role="button">大学党 伤不起</a>
      <a href="#" class="btn btn-primary " role="button">官方小组</a>
      <a href="#" class="btn btn-primary " role="button">好好学习 天天向上</a>
      <a href="#" class="btn btn-primary " role="button">大学党 伤不起</a>
      <a href="#" class="btn btn-primary " role="button">官方小组</a>
      <a href="#" class="btn btn-primary " role="button">好好学习 天天向上</a>
    </div>
  </div>

</div>
{% endblock %}

osdj/osb/templates/osb/index.html
{% extends "osb/base.html"%}
{% load static from staticfiles %}
{% block content %}
<div class="col-md-8">
<h4>话题精选</h4>
<ul class="list-unstyled">
	{% for topics in top_topics_list %}
	<li>
		<div class="topics-li">
			<div class="hidden-xs topics-like">
				<img src='{% static 'img/star.png' %}'/>	
				<br/>
				{{ topics.likeduser.count }}
			</div>
			<div class="topics-info greenlink">
				<h3><a href="#">{{ topics.headline }}</a></h3>	
				<p>{{ topics.description }}</p>
				<em><a href="/osb/home/{{topics.creator}}">{{ topics.creator }}</a>发布于<a href="#">老冰</a>{{ topics.group }}</em>
				<span>{{ topics.createdate }}</span>
			</div>
		</div>	
	</li>
	{% endfor %}
</ul>
<nav class="navcenter">
	<ul class="pagination">
		<li class="disabled"><a href="#">&laquo;</a></li>
		<li class="active"><a href="#">1</a></li>
		<li><a href="#">2</a></li>
		<li><a href="#">3</a></li>
		<li><a href="#">4</a></li>
		<li><a href="#">5</a></li>
		<li><a href="#">6</a></li>
		<li><a href="#">7</a></li>
		<li><a href="#">8</a></li>
		<li><a href="#">&raquo;</a></li>
	</ul>
</nav>
</div>
{% endblock %}

<!--right on desktop-->
{% block right%}
<div class="col-md-4">
<div class="panel panel-default ">
	<div class="panel-heading">战友最爱小组</div>
		<div class="panel-body">
			<ul class="list-unstyled">
				<li>
					<span class="badge badge-green">
					<a href="#">小组名字</a></span>现有<span class="badge badge-green">102301</span>人,共 
					<span class="badge badge-green">1928</span>个话题...
				</li> 
			</ul>
		</div>
	</div>

	<div class="panel panel-orange orange">
		<div class="panel-heading">最近加入战友</div>
			<div class="panel-body">
				<ul class="list-unstyled">
					<li>
					<span class="badge badge-orange"><a href="#">安明哲</a></span>
					曾经在陕西商洛服役
					<span class="badge badge-orange"><a href="#">1999</a></span>年入伍
					</li>	
				</ul>
			</div>
		</div>
	</div>
</div>
	{% endblock %}